services:
  app_dinenow:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - traefik_network
    labels:
      - "traefik.enable=false"
    depends_on:
      - pgsql_dinenow
  
  server_dinenow:
    image: nginx:alpine
    container_name: server_dinenow
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server_dinenow.rule=Host(`dinenow.test`)"
      - "traefik.http.routers.server_dinenow.entrypoints=https"
      - "traefik.http.routers.server_dinenow.tls=true"
      - "traefik.http.routers.server_dinenow.service=server_dinenow@docker"
      - "traefik.http.services.server_dinenow.loadbalancer.server.port=80"
    depends_on:
      - app_dinenow

  pgsql_dinenow:
    image: postgres:17.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dinenow_db
      POSTGRES_USER: dinenow
    ports:
      - "5432:5432"
    volumes:
      - pgsql_data_dinenow:/var/lib/postgresql/data
    networks:
      - traefik_network

volumes:
  pgsql_data_dinenow:

networks:
  traefik_network:
    external: true